server:
  port: 8104

spring:
  application:
    name: vg-ms-grade-management
  
  # Configuración de MongoDB Reactiva
  data:
    mongodb:
      uri: mongodb+srv://cristopherguzman:orTIWL10NmFAo3S5@cluster0.o8sc9.mongodb.net/AS231S5_PRS2?retryWrites=true&w=majority&appName=Cluster0
      database: AS231S5_PRS2
      # Configuración de conexión reactiva
      auto-index-creation: true
  
  # Configuración de Jackson para serialización JSON
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    deserialization:
      accept-single-value-as-array: true
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: America/Lima

# Configuración de logging
logging:
  level:
    root: INFO
    pe.edu.vallegrande.vg_ms_grade_management: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Información de la aplicación
info:
  app:
    name: Grade Management Service
    description: Microservicio de gestión de calificaciones según estándar MINEDU v8.0
    version: 8.0.0
    role: TEACHER EXCLUSIVE
